name: Build
on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: 16.10.0
      - uses: bahmutov/npm-install@v1.8.28
        with: { useRollingCache: true } # recommended for large projects
        env:
          CYPRESS_INSTALL_BINARY: 0 # no need to install the Cypress binary, we are already using the docker image in the e2e job

  # unit-test:
  #   needs: [install-dependencies]
  #   name: Run Unit Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: bahmutov/npm-install@v1.8.15
  #       with:
  #         useRollingCache: true
  #     - name: Run tests
  #       run: yarn test

  lint:
    needs: [install-dependencies]
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1.8.28
        with: { useRollingCache: true }
        env:
          CYPRESS_INSTALL_BINARY: 0
      - name: lint
        run: yarn lint

  typecheck:
    needs: [install-dependencies]
    name: Run Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1.8.28
        with: { useRollingCache: true }
        env:
          CYPRESS_INSTALL_BINARY: 0
      - name: typecheck
        run: yarn typecheck

  cypress-e2e-tests:
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    container: cypress/included:12.4.1 # save time on not having to install cypress
    steps:
      - uses: actions/checkout@v3

      - uses: bahmutov/npm-install@v1.8.28 # save time on dependencies
        with: { useRollingCache: true }

      - name: Cypress e2e tests ðŸ§ª
        uses: cypress-io/github-action@v5.0.8
        with:
          install: false # no need to install because of the above 2
          start: yarn start
          wait-on: 'http://localhost:3000'
          # if you want to enable parallelization
          # browser: chrome
          # record: true # records on cypress dashboard
          # group: e2e-tests
          # tag: e2e-tests
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

  cypress-component-tests:
    # if you want to enable parallelization
    # strategy:
    #   matrix:
    #     machines: [1, 2, 3, 4, 5]
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    container: cypress/included:12.4.1 # save time on not having to install cypress
    steps:
      - uses: actions/checkout@v3

      - uses: bahmutov/npm-install@v1.8.28 # save time on dependencies
        with: { useRollingCache: true }

      - name: Cypress component tests ðŸ§ª
        uses: cypress-io/github-action@v5.0.8
        with:
          # we have already installed everything
          install: false
          component: true
          browser: chrome
          # if you want to enable parallelization
          # record: true
          # parallel: true # parallelizes tests
          # group: component-tests
          # tag: component-test
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
