name: Build
on: push

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        cache: 'yarn'
    - uses: bahmutov/npm-install@v1
      with:
        useRollingCache: true # recommended for large projects

  unit-test:
    needs: install-dependencies
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
      - name: Run tests
        run: yarn test
    
  lint:
    needs: install-dependencies
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
      - name: lint
        run: yarn lint

  typecheck:
    needs: install-dependencies
    name : Run Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
      - name: typecheck
        run: yarn typecheck

  e2e-test:
    needs: [unit-test, lint, typecheck]
    runs-on: ubuntu-latest
    container: cypress/included:8.4.1 # save time on not having to install cypress
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1 # save time on dependencies
        with:
          useRollingCache: true
      - name: Cypress tests ðŸ§ª
        uses: cypress-io/github-action@v2
        with:
          install: false # no need to install because of the above 2
          start: yarn start
          wait-on: 'http://localhost:3000'

